
export const COMMAND_ALIASES = Object.freeze({
  DXF:'DXFOUT', DXFOUT:'DXFOUT', DXFIN:'DXFIN', DXFEXPORT:'DXFOUT', DXFIMPORT:'DXFIN',
  IM:'IMAGE', IMAGE:'IMAGE', CAL:'CALIBRATE', CALIBRATE:'CALIBRATE',
  IP:'UNDERLAY', UNDERLAY:'UNDERLAY',
  L:'LINE', LINE:'LINE', PL:'PLINE', PLINE:'PLINE', P:'PLINE',
  REC:'RECTANGLE', RECTANG:'RECTANGLE', RECTANGLE:'RECTANGLE', C:'CIRCLE', CIRCLE:'CIRCLE',
  A:'ARC', ARC:'ARC',
  M:'MOVE', MOVE:'MOVE', CO:'COPY', COPY:'COPY', CP:'COPY', RO:'ROTATE', ROTATE:'ROTATE',
  SC:'SCALE', SCALE:'SCALE', MI:'MIRROR', MIRROR:'MIRROR',
  AR:'ARRAY', ARRAY:'ARRAY',
  E:'ERASE', ERASE:'ERASE', DEL:'ERASE', DELETE:'ERASE',
  O:'OFFSET', OFFSET:'OFFSET',
  F:'FILLET', FILLET:'FILLET', CHA:'CHAMFER', CHAMFER:'CHAMFER',
  TR:'TRIM', TRIM:'TRIM', EX:'EXTEND', EXTEND:'EXTEND', S:'SELECT', SELECT:'SELECT',
  J:'JOIN', JOIN:'JOIN', X:'EXPLODE', EXPLODE:'EXPLODE',
  ST:'STRETCH', STRETCH:'STRETCH',
  Z:'ZOOMEXTENTS', ZE:'ZOOMEXTENTS',
  UN:'UNITS', UNITS:'UNITS', DDUNITS:'UNITS',
  PLT:'PLOT', PLOT:'PLOT', PRINT:'PLOT',
  DI:'DIST', DIST:'DIST', DISTANCE:'DIST',
  DLI:'DIMLINEAR', DIMLINEAR:'DIMLINEAR', DIMLIN:'DIMLINEAR',
  DAL:'DIMALIGNED', DIMALIGNED:'DIMALIGNED', DIMALI:'DIMALIGNED',
  DRA:'DIMRADIUS', DIMRADIUS:'DIMRADIUS', DIMRAD:'DIMRADIUS',
  DDI:'DIMDIAMETER', DIMDIAMETER:'DIMDIAMETER', DIMDIA:'DIMDIAMETER',
  DST:'DIMSTYLE', DIMSTYLE:'DIMSTYLE', DDIM:'DIMSTYLE',
  T:'TEXT', TEXT:'TEXT', DT:'TEXT', DTEXT:'TEXT',
  MT:'MTEXT', MTEXT:'MTEXT',
  AA:'AREA', AREA:'AREA',
  ID:'ID', LI:'LIST', LIST:'LIST',
});

export function resolveCommandName(value) {
  return COMMAND_ALIASES[String(value).trim().toUpperCase()] || null;
}
